# Generated by Django 2.2.4 on 2019-08-12 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0011_auto_20190811_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0.21, max_digits=5)),
                ('date', models.DateField(auto_now_add=True)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('paid', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('is_credit_invoice', models.BooleanField(default=False)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UNIT')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, help_text='If the VAT% is not equal to the overall VAT rate', max_digits=7, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.Invoice')),
            ],
        ),
    ]
